name: Build Flash Boot Tool
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend deps
        run: |
          cd backend
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build backend.exe
        run: |
          cd backend
          pyinstaller --onefile --name backend main.py

      - name: Verify backend.exe
        shell: cmd
        run: |
          if not exist backend\dist\backend.exe (
            echo backend.exe not found!
            exit 1
          )
          dir backend\dist

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install frontend deps
        run: |
          cd frontend
          npm install

      - name: Build React
        run: |
          cd frontend
          npm run build

      - name: Build Electron
        run: |
          cd frontend
          npm run dist

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Flash-Boot-Tool
          path: frontend/release/*.exe
