name: Build Flash

on:
 push:
  branches:
  - main

jobs:
 build:
  runs-on: windows-latest
  steps:
  # =========================
  # CHECKOUT
  # =========================
  - name: Checkout
    uses: actions/checkout@v4

  # =========================
  # NODE
  # =========================
  - name: Setup Node
    uses: actions/setup-node@v4
    with:
      node-version: 20

  # =========================
  # FRONTEND (VITE)
  # =========================
  - name: Install frontend deps
    working-directory: frontend-c
    run: npm install

  - name: Build React
    working-directory: frontend-c
    run: npm run build

  # =========================
  # ELECTRON
  # =========================
  - name: Install Electron deps
    working-directory: electron
    run: npm install

  # =========================
  # MSVC
  # =========================
  - name: Setup MSVC
    uses: ilammy/msvc-dev-cmd@v1

  # =========================
  # BUILD C++ BACKEND
  # =========================
  - name: Build C++ backend
    working-directory: backend-cpp
    shell: cmd
    run: |
      if not exist build mkdir build
      cd build
      cmake -G "Visual Studio 17 2022" ..
      cmake --build . --config Release

  # =========================
  # DEBUG BACKEND OUTPUT
  # =========================
  - name: Show backend files
    shell: powershell
    run: |
      Get-ChildItem backend-cpp/build -Recurse

  # =========================
  # COPY BACKEND EXE
  # =========================
  - name: Copy backend exe
    shell: powershell
    run: |
      New-Item -ItemType Directory -Force -Path "electron/resources/backend"

      Copy-Item `
        "backend-cpp/build/Release/FlashTool.exe" `
        "electron/resources/backend/FlashTool.exe" `
        -Force

  # =========================
  # COPY REACT BUILD
  # =========================
  - name: Copy frontend build
    shell: powershell
    run: |
      New-Item -ItemType Directory -Force -Path "electron/frontend"

      Copy-Item `
        "frontend-c/dist/*" `
        "electron/frontend/" `
        -Recurse -Force

  # =========================
  # SHOW FILES BEFORE PACKAGING
  # =========================
  - name: Show Electron Files
    shell: powershell
    run: |
      Get-ChildItem electron -Recurse

  # =========================
  # BUILD ELECTRON
  # =========================
  - name: Build Electron Windows
    working-directory: electron
    run: npm run dist

  # =========================
  # SHOW RELEASE FILES
  # =========================
  - name: Show Release Files
    shell: powershell
    run: |
      Get-ChildItem electron/release -Recurse

  # =========================
  # ARTIFACT
  # =========================
  - name: Upload Windows Artifact
    uses: actions/upload-artifact@v4
    with:
      name: Flash-Boot-Tool-Windows
      path: electron/release/*.exe
